### ISSUE TITLE
unreachable return

### ISSUE THREAD

**Issue by GonzRon** [burnsfisher/hubitat-integration-skill#3]
Hi there,

in case you were wondering, this is the unreachable return statement

https://github.com/burnsfisher/hubitat-integration-skill/blob/a609251239364763e3e9702f7d7840126196aef7/__init__.py#L260

**Comment by burnsfisher** [comment]
Thanks!  Probably forgot to remove it when I added the error clause.  I'll merge your changes after trying it out for a while.
