### ISSUE TITLE
poll endpoint no longer available

### ISSUE THREAD

**Issue by GonzRon** [burnsfisher/hubitat-integration-skill#5]
https://github.com/burnsfisher/hubitat-integration-skill/blob/master/__init__.py#L291

please note:

[e28bfc2526212dd40306470438d182edcc1c0c19](https://github.com/burnsfisher/hubitat-integration-skill/commit/e28bfc2526212dd40306470438d182edcc1c0c19#diff-f0074871f9bda032ce496cc69c73f9db08a01e419dbe255d6fdcd25a088130c4L296)

the poll endpoint is no longer available

**Comment by burnsfisher** [comment]
Appears to work ok in GonzRon branch.  I'll let it run in my office for a while before merging.
